version: '3'

services:
  app:
    build: .
    container_name: clean-arch-node-api
    image: clean-arch-node-api
    command: code/.docker/entrypoint.sh
    volumes:
      - ../:/home/node/app
    ports:
      - 3000:3000
